version: "3.9"
services:
  app:
    build: 
      context: .
      target: dev
    container_name: app
    env_file: .env
    ports:
      - 50052:50052
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - m0n3y-api

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - m0n3y-api

networks:
  m0n3y-api:
    driver: bridge