CREATE TABLE IF NOT EXISTS users(
   user_id TEXT PRIMARY KEY,
   first_name TEXT,
   last_name TEXT,
   email TEXT NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
   updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
   deleted_at TIMESTAMP WITH TIME ZONE
);